=== AlexlopeGome/ActividadesDAM/Lenguaja de marcas/XMLBLueprint/videojuegos2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="videojuegos2">
        <xs:complexType>
            <xs:sequence>
                <xs:element  minOccurs="1" maxOccurs="99999" ref="videojuego"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="videojuego">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element minOccurs="1" ref="precio"/>
                <xs:element ref="moneda"/>
                <xs:element ref="consola"/>
                <xs:element ref="web"/>
            </xs:sequence>
            <xs:attribute name="cod" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="precio" type="xs:integer"/>
    <xs:simpleType name="moneda" base="xs:string" derivedBy="list"/>
    <moneda>â‚¬ $</moneda>
   </xs:simpleType>
    <xs:element name="consola" type="xs:string"/>
    <xs:element name="web" type="xs:NCName"/>
</xs:schema>

=== AlexlopeGome/ActividadesDAM/Lenguaja de marcas/XMLBLueprint/videojuegos2.xml
<?xml version="1.0" encoding="utf-8"?>
<videojuegos2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Alejandro/Desktop/DAM/REPOSITOS/ActividadesDAM/Lenguaja%20de%20marcas/XMLBLueprint/videojuegos2.xsd">
	<videojuego cod="1234">
		<nombre>Super Mario 3D  LAN</nombre>
		<precio>40</precio>
		<moneda>€</moneda>
		<consola>Nintendo 3D</consola>
		<web>www.Supermario3s.com</web>
	</videojuego >
		<videojuego cod="1459">
		<nombre>Formula 1 2022</nombre>
		<precio>60</precio>
		<moneda>€</moneda>
		<consola>XBOX</consola>
		<web>www.f1games.com</web>
	</videojuego>
</videojuegos2>
